# Trigger build 1
---
name: isoimagewriter
base: core22
adopt-info: isoimagewriter
grade: stable
confinement: strict
apps:
    isoimagewriter:
        # extensions:
        # - kde-neon
        command: usr/bin/isoimagewriter
        desktop: usr/share/applications/org.kde.isoimagewriter.desktop
        common-id: org.kde.isoimagewriter
        plugs:
        - home
        - raw-usb
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        - udisks2
        - optical-drive
        - gpg-keys
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.58.3
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-110-qt-5-15-11-core22:
        content: kf5-5-110-qt-5-15-11-core22-all
        interface: content
        default-provider: kf5-5-110-qt-5-15-11-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    SNAP_SAVE_DATA: $SNAP_USER_DATA
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.isoimagewriter
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-110-qt-5-15-11-core22
        build-snaps:
        - kf5-5-110-qt-5-15-11-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-110-qt-5-15-11-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-110-qt-5-15-11-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-110-qt-5-15-11-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-110-qt-5-15-11-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    isoimagewriter:
        after:
        - kde-neon
        source: .
        source-type: local
        plugin: cmake
        build-packages:
        - cmake
        - libgpgme-dev
        - libgpgmepp-dev
        - libgpg-error-dev
        stage-packages:
        - libgpgme11
        - libgpgmepp6
        - libqgpgme7
        - gpg
        cmake-parameters:
        - -DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-110-qt-5-15-11-core22-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins/"
        - "-DUSE_KAUTH=off"
        parse-info:
        - usr/share/metainfo/org.kde.isoimagewriter.appdata.xml
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-usr/share/lintian"
        build-environment: &id005
        - *id001
        - *id002
        - *id003
        - *id004
    # cleanup:
    #     after:
    #     - isoimagewriter
    #     plugin: nil
    #     build-snaps:
    #     - kde-frameworks-5-99-qt-5-15-7-core20
    #     override-prime: |
    #         set -eux
    #         for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
    #             cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
    #         done
    #         find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
    #         find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
